export const DISC_LIST_REQUEST = 'DISC_LIST_REQUEST'
export const DISC_LIST_SUCCESS = 'DISC_LIST_SUCCESS'
export const DISC_LIST_FAIL = 'DISC_LIST_FAIL'

export const DISC_DETAILS_REQUEST = 'DISC_DETAILS_REQUEST'
export const DISC_DETAILS_SUCCESS = 'DISC_DETAILS_SUCCESS'
export const DISC_DETAILS_FAIL = 'DISC_DETAILS_FAIL'

export const DISC_DELETE_REQUEST = 'DISC_DELETE_REQUEST'
export const DISC_DELETE_SUCCESS = 'DISC_DETAILS_SUCCESS'
export const DISC_DELETE_FAIL = 'DISC_DELETE_FAIL'

export const DISC_CREATE_REQUEST = 'DISC_CREATE_REQUEST'
export const DISC_CREATE_SUCCESS = 'DISC_CREATES_SUCCESS'
export const DISC_CREATE_FAIL = 'DISC_CREATE_FAIL'
export const DISC_CREATE_RESET = 'DISC_CREATE_RESET'

export const DISC_UPDATE_REQUEST = 'DISC_UPDATE_REQUEST'
export const DISC_UPDATE_SUCCESS = 'DISC_UPDATES_SUCCESS'
export const DISC_UPDATE_FAIL = 'DISC_UPDATE_FAIL'
export const DISC_UPDATE_RESET = 'DISC_UPDATE_RESET'

export const DISC_CREATE_REVIEW_REQUEST = 'DISC_CREATE_REVIEW_REQUEST'
export const DISC_CREATE_REVIEW_SUCCESS = 'DISC_CREATE_REVIEWS_SUCCESS'
export const DISC_CREATE_REVIEW_FAIL = 'DISC_CREATE_REVIEW_FAIL'
export const DISC_CREATE_REVIEW_RESET = 'DISC_CREATE_REVIEW_RESET'

export const DISC_TOP_REQUEST = 'DISC_TOP_REQUEST'
export const DISC_TOP_SUCCESS = 'DISC_TOPS_SUCCESS'
export const DISC_TOP_FAIL = 'DISC_TOP_FAIL'
