export const DISC_LIST_REQUEST = 'DISC_LIST_REQUEST'
export const DISC_LIST_SUCCESS = 'DISC_LIST_SUCCESS'
export const DISC_LIST_FAIL = 'DISC_LIST_FAIL'

export const DISC_DETAILS_REQUEST = 'DISC_DETAILS_REQUEST'
export const DISC_DETAILS_SUCCESS = 'DISC_DETAILS_SUCCESS'
export const DISC_DETAILS_FAIL = 'DISC_DETAILS_FAIL'

export const DISC_DELETE_REQUEST = 'DISC_DELETE_REQUEST'
export const DISC_DELETE_SUCCESS = 'DISC_DETAILS_SUCCESS'
export const DISC_DELETE_FAIL = 'DISC_DELETE_FAIL'